### ISSUE TITLE
HTML für TicTacToe

### ISSUE THREAD

**Issue by tkilla77** [tkilla77/bottom_tictactoe#1]
- [x] neue Datei `tictactoe.html` erstellen
- [x] [Grundgerüst](https://wiki.selfhtml.org/wiki/HTML/Tutorials/Grundger%C3%BCst) für HTML einfüllen.
- [x] Ein einfaches Spielfeld mit HTML schreiben. Zum Beispiel: 3 Zeilen à 3 Zellen

```html
<ttt-zeile><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle></ttt-zeile>
<ttt-zeile><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle></ttt-zeile>
<ttt-zeile><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle><ttt-zelle></ttt-zelle></ttt-zeile>
```
- [x] Das ganze im Browser anzeigen.

**Comment by allegroegnach** [comment]
Mache bitte alles!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
