### ISSUE TITLE
Formatiere das Spiel mit CSS

### ISSUE THREAD

**Issue by tkilla77** [tkilla77/bottom_tictactoe#2]
- [x] [Füge eine CSS-Datei zu deinem HTML dazu](https://wiki.selfhtml.org/wiki/CSS/Tutorials/Einstieg/Stylesheets_einbinden#Einbinden_eines_externen_Stylesheets)
- [x] Füge CSS dazu, um deine `<ttt-zeile>` und `<ttt-zelle>` Elemente zu formatieren.

Tipps folgen.

**Comment by tkilla77** [comment]
Ich habe schon mal ein paar Formatierungsregeln hinzugefügt. Sie werden in der Datei `tictactoe.css` definiert.

- [x] Du solltest nun noch für die richtigen Farben und Ränder sorgen. Lies auf SelfHTML über die [Hintergrundfarbe](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/background-color), die du für die Element `ttt-brett` und `ttt-zelle` festlegen kannst.
- [x] Mit [border-radius](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/border-radius) für abgerundete Ecken sorgen.
- [x] Wenn du noch mehr tun willst, kannst du mit [box-shadow](https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/box-shadow) noch einen Schatten-Effekt zu den Zellen hinzufügen.

**Comment by allegroegnach** [comment]
Aufgaben gelöst
